# Generated by Django 3.2.6 on 2022-08-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(default='', max_length=20, verbose_name='feature_name')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='intent name')),
                ('user', models.CharField(default='no user', max_length=20, verbose_name='intent user')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_content', models.CharField(default='', max_length=20, verbose_name='feature_content')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='Intent.feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_intent', to='Intent.intent'),
        ),
    ]
