# Generated by Django 3.2.6 on 2022-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20220808_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sentence',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
