# Generated by Django 3.2.6 on 2022-08-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sentence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
