# Generated by Django 3.2.6 on 2022-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inputTokenize',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='matchedEntity',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
