# Generated by Django 3.2.6 on 2022-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20220808_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paramToAsk',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
